#!/bin/sh /etc/rc.common
# ShellCheck cannot see hotplug2 reading this ordering contract.
# shellcheck disable=SC2034
START=50

SSD=start-stop-daemon
NAME=mochad
PIDF=/var/run/$NAME.pid
PROG=/usr/sbin/$NAME

start() {
	$SSD -S -m -p $PIDF -q -x $PROG &
}

stop() {
	$SSD -K -p $PIDF
}
