.TH MOCHAD 1
.SH NAME
mochad \- X10 controller TCP gateway
.SH SYNOPSIS
.B mochad
[options]
.SH DESCRIPTION
.B mochad
connects supported X10 USB controllers to its legacy TCP interfaces.
.SH INSTALLATION
Package installation only copies files.  Native service and udev integration
are performed explicitly by
.BR mochad-redux-setup (8).
.SH SEE ALSO
.BR mochad-redux-setup (8)
